export const TEMPLATE_TYPE_API_VALUE_MAP = {
  presentation: 'presentation',
  cardnews: 'card_news',
  detailPage: 'detail_page',
  socialSquare: 'social_media_square',
  instagramFeedPost: 'instagram_feed',
  youtubeChannelArt: 'youtube_cover',
  wallpaperMobile: 'wallpaper_mobile',
  wallpaperPc: 'wallpaper_pc',
  infographic: 'infographic_hor',
  bookCover: 'book_cover',
  logoProfile: ['logo', 'social_media_square'],
  eventPopup: 'groobee_big',
  youtubeThumbnail: 'youtube_thumb',
  youtubeShorts: 'youtube_video_shorts',
  youtubeVideo: 'youtube_video_full',
  instagramVideoPost: 'instagram_video_post',
  instagramReels: 'instagram_video_reels',
  instagramVideoStory: 'instagram_video_story',
  facebookPostHorizontal: 'facebook_video_horizontal',
  facebookPostSquare: 'facebook_video_square',
  facebookStory: 'facebook_story',
  tiktokVideo: 'tiktok_video',
  printPosterVertical: ['placard_poster_ver', 'poster_ver_print', 'web_post_ver_poster'],
  printPosterHorizontal: ['poster_hor_print', 'web_post_hor_poster'],
  printPlacardHorizontal: ['placard_hor', 'web_banner_hor'],
  printPlacardVertical: ['placard_ver', 'web_banner_ver'],
  printBannerGeneral: ['banner', 'web_post_ver'],
  printPlacardHorizontalPoster: [
    'poster_hor_print',
    'web_post_hor_poster',
    'placard_poster_hor',
    'real_print_hor',
    'web_flyer_single_hor',
  ],
  printPlacardVerticalPoster: [
    'placard_poster_ver',
    'poster_ver_print',
    'web_flyer_single',
    'web_post_ver_poster',
  ],
  printBusinessCardHorizontal: 'business_card_hor',
  printBusinessCardVertical: ['business_card_ver', 'digital_name_card_ver'],
  printStickerSquare: 'print_sticker_square',
  printPostcardVertical: 'post_card_102_152',
  printPostcardHorizontal: 'post_card_152_102',
  printPostcardFoldHorizontal: 'post_card_fold_hor',
  printPostcardFoldVertical: 'post_card_fold_ver',
  printMemoPadSquare: [
    'instagram_feed',
    'ricecake_memo_paper_square',
    'social_media_square',
  ],
  printMemoPadVertical: 'ricecake_memo_paper_ver_rect',
  printMemoPadHorizontal: 'ricecake_memo_paper_hor_rect',
  printPhoneCaseClear: 'phone_case_clear',
  printPhoneCaseHard: 'phone_case_hard',
};

export const VERIFIED_TEMPLATE_TYPES = {
  banner: true,
  book_cover: true,
  business_card_hor: true,
  business_card_ver: true,
  card_news: true,
  detail_page: true,
  digital_name_card_ver: true,
  facebook_story: true,
  facebook_video_horizontal: true,
  facebook_video_square: true,
  groobee_big: true,
  infographic_hor: true,
  instagram_feed: true,
  instagram_video_post: true,
  instagram_video_reels: true,
  instagram_video_story: true,
  logo: true,
  phone_case_clear: true,
  phone_case_hard: true,
  placard_hor: true,
  placard_poster_hor: true,
  placard_poster_ver: true,
  placard_ver: true,
  post_card_102_152: true,
  post_card_152_102: true,
  post_card_fold_hor: true,
  post_card_fold_ver: true,
  poster_hor_print: true,
  poster_ver_print: true,
  presentation: true,
  print_sticker_square: true,
  real_print_hor: true,
  ricecake_memo_paper_hor_rect: true,
  ricecake_memo_paper_square: true,
  ricecake_memo_paper_ver_rect: true,
  social_media_square: true,
  tiktok_video: true,
  wallpaper_mobile: true,
  wallpaper_pc: true,
  web_banner_hor: true,
  web_banner_ver: true,
  web_flyer_single: true,
  web_flyer_single_hor: true,
  web_post_hor: true,
  web_post_hor_poster: true,
  web_post_ver: true,
  web_post_ver_poster: true,
  youtube_cover: true,
  youtube_thumb: true,
  youtube_video_full: true,
  youtube_video_shorts: true,
};

const WEB_PURPOSE = 'WEB';
const VIDEO_PURPOSE = 'VIDEO';
const PRINT_PURPOSE = 'PRINT';
const PREMIUM_TIER = 'PREMIUM';

function createTemplate(group, label, value, apiValue, purpose, tier = PREMIUM_TIER) {
  return {
    group,
    label,
    value,
    apiValue,
    purpose,
    tier,
  };
}

export const TEMPLATE_TYPE_MAP = [
  createTemplate('웹', '프레젠테이션', 'presentation', 'presentation', WEB_PURPOSE),
  createTemplate('웹', '카드뉴스', 'cardnews', 'card_news', WEB_PURPOSE),
  createTemplate('웹', '상세페이지', 'detailPage', 'detail_page', WEB_PURPOSE),
  createTemplate('웹', '소셜 미디어 정사각형', 'socialSquare', 'social_media_square', WEB_PURPOSE),
  createTemplate('웹', '인스타그램 새 피드 게시물', 'instagramFeedPost', 'instagram_feed', WEB_PURPOSE),
  createTemplate('웹', '유튜브 채널아트', 'youtubeChannelArt', 'youtube_cover', WEB_PURPOSE),
  createTemplate('웹', '배경화면 (9:19) 모바일', 'wallpaperMobile', 'wallpaper_mobile', WEB_PURPOSE),
  createTemplate('웹', '배경화면 (16:9) PC', 'wallpaperPc', 'wallpaper_pc', WEB_PURPOSE),
  createTemplate('웹', '인포그래픽', 'infographic', 'infographic_hor', WEB_PURPOSE),
  createTemplate('웹', '북커버', 'bookCover', 'book_cover', WEB_PURPOSE),
  createTemplate('웹', '로고/프로필', 'logoProfile', ['logo', 'social_media_square'], WEB_PURPOSE),
  createTemplate('웹', '이벤트 팝업', 'eventPopup', 'groobee_big', WEB_PURPOSE),
  createTemplate('동영상', '유튜브 썸네일', 'youtubeThumbnail', 'youtube_thumb', VIDEO_PURPOSE),
  createTemplate('동영상', '유튜브 쇼츠', 'youtubeShorts', 'youtube_video_shorts', VIDEO_PURPOSE),
  createTemplate('동영상', '유튜브 영상', 'youtubeVideo', 'youtube_video_full', VIDEO_PURPOSE),
  createTemplate('동영상', '인스타그램 게시물', 'instagramVideoPost', 'instagram_video_post', VIDEO_PURPOSE),
  createTemplate('동영상', '인스타그램 릴스', 'instagramReels', 'instagram_video_reels', VIDEO_PURPOSE),
  createTemplate('동영상', '인스타그램 스토리', 'instagramVideoStory', 'instagram_video_story', VIDEO_PURPOSE),
  createTemplate('동영상', '페이스북 게시물 (가로형)', 'facebookPostHorizontal', 'facebook_video_horizontal', VIDEO_PURPOSE),
  createTemplate('동영상', '페이스북 게시물 (정사각형)', 'facebookPostSquare', 'facebook_video_square', VIDEO_PURPOSE),
  createTemplate('동영상', '페이스북 스토리', 'facebookStory', 'facebook_story', VIDEO_PURPOSE),
  createTemplate('동영상', 'TikTok', 'tiktokVideo', 'tiktok_video', VIDEO_PURPOSE),
  createTemplate('인쇄', '일반 포스터 세로형', 'printPosterVertical', ['placard_poster_ver', 'poster_ver_print', 'web_post_ver_poster'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 포스터 가로형', 'printPosterHorizontal', ['poster_hor_print', 'web_post_hor_poster'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 현수막 가로형', 'printPlacardHorizontal', ['placard_hor', 'web_banner_hor'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 현수막 세로형', 'printPlacardVertical', ['placard_ver', 'web_banner_ver'], PRINT_PURPOSE),
  createTemplate('인쇄', '배너 일반 배너', 'printBannerGeneral', ['banner', 'web_post_ver'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 현수막 가로 포스터형', 'printPlacardHorizontalPoster', ['poster_hor_print', 'web_post_hor_poster', 'placard_poster_hor', 'real_print_hor', 'web_flyer_single_hor'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 현수막 세로 포스터형', 'printPlacardVerticalPoster', ['placard_poster_ver', 'poster_ver_print', 'web_flyer_single', 'web_post_ver_poster'], PRINT_PURPOSE),
  createTemplate('인쇄', '일반 명함 가로형', 'printBusinessCardHorizontal', 'business_card_hor', PRINT_PURPOSE),
  createTemplate('인쇄', '일반 명함 세로형', 'printBusinessCardVertical', ['business_card_ver', 'digital_name_card_ver'], PRINT_PURPOSE),
  createTemplate('인쇄', '스티커(정사각형)', 'printStickerSquare', 'print_sticker_square', PRINT_PURPOSE),
  createTemplate('인쇄', '엽서카드 세로형', 'printPostcardVertical', 'post_card_102_152', PRINT_PURPOSE),
  createTemplate('인쇄', '엽서카드 가로형', 'printPostcardHorizontal', 'post_card_152_102', PRINT_PURPOSE),
  createTemplate('인쇄', '엽서카드 2단 가로형', 'printPostcardFoldHorizontal', 'post_card_fold_hor', PRINT_PURPOSE),
  createTemplate('인쇄', '엽서카드 2단 세로형', 'printPostcardFoldVertical', 'post_card_fold_ver', PRINT_PURPOSE),
  createTemplate('인쇄', '메모지 정비율', 'printMemoPadSquare', ['instagram_feed', 'ricecake_memo_paper_square', 'social_media_square'], PRINT_PURPOSE),
  createTemplate('인쇄', '메모지 세로형', 'printMemoPadVertical', 'ricecake_memo_paper_ver_rect', PRINT_PURPOSE),
  createTemplate('인쇄', '메모지 가로형', 'printMemoPadHorizontal', 'ricecake_memo_paper_hor_rect', PRINT_PURPOSE),
  createTemplate('인쇄', '폰 케이스 투명 폰케이스', 'printPhoneCaseClear', 'phone_case_clear', PRINT_PURPOSE),
  createTemplate('인쇄', '폰 케이스 하드 폰케이스', 'printPhoneCaseHard', 'phone_case_hard', PRINT_PURPOSE),
];
